services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mel-bouh/data/mysql